#!/bin/sh

echo "This will take some time."

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install automake autoconf pkg-config libcurl4-openssl-dev libjansson-dev libssl-dev libgmp-dev make g++ git libgmp-dev -y

git clone https://github.com/magi-project/m-cpuminer-v2.git

cd m-cpuminer-v2

./autogen.sh
./configure CFLAGS="-O3" CXXFLAGS="-O3"
make

echo "Installed. Usage is ./m-minerd while inside the 'm-cpuminer-v2' folder."