name: Github Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        
      - name: Install jsdoc
        run: |
          npm i -g jsdoc
          cd site
          cd projects
          git clone https://github.com/Arkanic/minicheck --depth=1
          jsdoc minicheck.js -d .
      
      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1.6.1
        with:
          path-to-root: ./site
          base-url-path: https://Arkanic.github.io/
      
      - name: Generate Projects Index
        run: |
          chmod a+x ./genIndex.sh
          ./genIndex.sh
      
      - name: Install dependencies
        run: |
          sudo npm i -g dessi
      
      - name: Generate SSIs
        run: dessi --root=./site --target=./dist --source=./site
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
