name: Github Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Make output folder
        run: mkdir dist
      
      - name: Add site contents
        run: cp -r site/* dist

      - name: add phraser
        run: |
          git clone https://github.com/Arkanic/phraser
          mv phraser/phraser ./dist/phraser
      
      - name: Add Keeweb
        run: cp -r keeweb ./dist/keeweb
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
